name: 'Pull Request title rules'
description: 'Github action to enforce Pull Request title conventions'
author: 'Ygor Galeno(forked from deepakputhraya)'
inputs:
  regex:
    description: 'Regex to validate the pull request title'
    required: false
    default: '.+'
  allowed_prefixes:
    description: 'Comma separated list of prefix allowed to be used in title. eg: feat, fix'
    required: false
    default: ''
  ignored_prefixes:
    description: 'Comma separated list of prefix should be ignored by action in title. eg: wip'
    required: false
    default: 'wip'
  prefix_case_sensitive:
    description: 'Are the allowed & ignored prefixes case sensitive?'
    required: false
    default: 'false'
  github_token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
    required: false
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/bundle.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
