name: main
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    name: Check
    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Validate
        uses: ./
        with:
          github_token: ${{ github.token }}
