name: main
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    # Job name is Greeting
    name: Check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Validate
        uses: ./
        with:
          github_token: ${{ github.token }}
